title: GEO
baseurl: "/GEO" # the subpath of your site
url: "http://generative-engines.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed